import yaml
from bot.parser import ParamRecord
from bot.emitter import emit_data_text


def test_krkn_hub_omits_absent_optional_fields():
    recs = [
        ParamRecord(name="ACTION", default="node_stop", type="enum"),
        ParamRecord(name="EXCLUDE_LABEL", type="string"),
    ]
    descs = {"ACTION": "Action to run.", "EXCLUDE_LABEL": "Nodes to exclude."}
    text = emit_data_text("node-scenarios", "krkn-hub", recs, descs, source_ref="abc123")
    data = yaml.safe_load(text)
    assert data["source_repo"] == "krkn-hub"
    assert data["source_ref"] == "abc123"
    assert data["params"][0] == {
        "name": "ACTION", "description": "Action to run.", "type": "enum", "default": "node_stop",
    }
    assert "default" not in data["params"][1]
    assert "required" not in data["params"][0]


def test_group_is_emitted_when_present():
    recs = [ParamRecord(name="wait-duration", default="1", group="general")]
    p = yaml.safe_load(emit_data_text(
        "globals", "krknctl", recs, {"wait-duration": "Waits."}, "r"))["params"][0]
    assert p["group"] == "general"


def test_group_is_omitted_when_absent():
    """Per-scenario params have no group and must not gain an empty key."""
    p = yaml.safe_load(emit_data_text(
        "node-scenarios", "krkn-hub", [ParamRecord(name="ACTION")],
        {"ACTION": "Act."}, "r"))["params"][0]
    assert "group" not in p


def test_krknctl_includes_required_and_possible_values():
    recs = [ParamRecord(name="CLOUD", type="enum", default="aws",
                        required=True, allowed_values=["aws", "gcp"])]
    descs = {"CLOUD": "Cloud platform."}
    text = emit_data_text("svc", "krknctl", recs, descs, source_ref="x")
    p = yaml.safe_load(text)["params"][0]
    assert p["possible_values"] == ["aws", "gcp"]
    assert p["required"] is True


def test_output_is_deterministic():
    recs = [ParamRecord(name="A", default="1", type="number")]
    descs = {"A": "An a."}
    t1 = emit_data_text("s", "krkn-hub", recs, descs, source_ref="r")
    t2 = emit_data_text("s", "krkn-hub", recs, descs, source_ref="r")
    assert t1 == t2
    assert t1.startswith("# Generated by krkn-docs-bot. Do not edit by hand.\n")
