from pathlib import Path
import yaml

_HEADER = "# Generated by krkn-docs-bot. Do not edit by hand.\n"


def _param_dict(rec, description, source):
    d = {"name": rec.name, "description": description}
    # Only global params have a group. It travels in the data so one file can
    # hold every group and the shortcode filters on it.
    if rec.group is not None:
        d["group"] = rec.group
    if rec.type is not None:
        d["type"] = rec.type
    if rec.default is not None:
        d["default"] = rec.default
    if source == "krknctl":
        if rec.allowed_values:
            d["possible_values"] = list(rec.allowed_values)
        d["required"] = bool(rec.required)
    return d


def emit_data_text(scenario, source, records, descriptions, source_ref):
    body = {
        "source_repo": source,
        "source_ref": source_ref,
        "params": [_param_dict(r, descriptions[r.name], source) for r in records],
    }
    dumped = yaml.dump(body, sort_keys=False, default_flow_style=False,
                       allow_unicode=True, width=4096)
    return _HEADER + dumped


def load_descriptions(path):
    """name -> description from a generated data file, or {} if it is not there.
    Reads back what emit_data_file writes."""
    path = Path(path)
    if not path.exists():
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return {p["name"]: p.get("description", "") for p in data.get("params", [])}


def emit_data_file(out_root, scenario, source, records, descriptions, source_ref):
    path = Path(out_root) / "data" / "params" / scenario / f"{source}.yaml"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(emit_data_text(scenario, source, records, descriptions, source_ref),
                    encoding="utf-8")
    return path
