from pathlib import Path
import yaml

HEADER = "# Generated by krkn-docs-bot. Do not edit by hand.\n"


# Only descriptions the bot could not take from source. env-comment is the
# source; krknctl counts here because on the krkn-hub page it is the other one.
_FALLBACK_SOURCES = ("published-table", "llm", "krknctl", "crd-field",
                     "hub-doc")


def _escape(text):
    """< and > for raw HTML, { for Hugo shortcodes. Never &, so a re-run stays
    idempotent: the entities contain none of the escaped characters."""
    if not text:
        return text
    return text.replace("<", "&lt;").replace(">", "&gt;").replace("{", "&#123;")


def _param_dict(rec, description, source, scenario):
    # The one sink every source's description passes through, so it is the only
    # place escaping has to live.
    d = {"name": rec.name, "description": _escape(description)}
    if rec.description_source in _FALLBACK_SOURCES:
        d["description_source"] = rec.description_source
    # Only global params have a group. It travels in the data so one file can
    # hold every group and the shortcode filters on it.
    if rec.group is not None:
        d["group"] = rec.group
    if rec.type is not None:
        d["type"] = rec.type
    if rec.default is not None:
        d["default"] = rec.default
    # The krkn-hub tab is the env-var view, so it shows no CLI flag even if one
    # was borrowed. name stays the env var: drift_scanner matches on it.
    if source != "krkn-hub" and rec.flag and rec.flag != rec.name:
        d["flag"] = rec.flag
    # Not source-gated: whichever source knows these should say so on its tab.
    if rec.secret:
        d["secret"] = True
    if rec.allowed_values:
        d["possible_values"] = list(rec.allowed_values)
    # Globals are all optional. A CRD column record carries required=None,
    # because requiredness means nothing for a display column.
    if scenario != "globals" and rec.required is not None:
        d["required"] = bool(rec.required)
    return d


def emit_data_text(scenario, source, records, descriptions, source_ref):
    body = {
        "source_repo": source,
        "source_ref": source_ref,
        "params": [_param_dict(r, descriptions[r.name], source, scenario) for r in records],
    }
    dumped = yaml.dump(body, sort_keys=False, default_flow_style=False,
                       allow_unicode=True, width=4096)
    return HEADER + dumped


def load_descriptions(path):
    """name -> description from a generated data file, or {} if it is not there.
    Reads back what emit_data_file writes."""
    path = Path(path)
    if not path.exists():
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return {p["name"]: p.get("description", "") for p in data.get("params", [])}


def load_previous(path):
    """name -> the whole previous row. load_descriptions returns descriptions
    only, which loses the type and provenance the published table supplies once:
    the shortcode replaces that table in the same run that reads it."""
    path = Path(path)
    if not path.exists():
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return {p["name"]: p for p in data.get("params", [])}


def emit_data_file(out_root, scenario, source, records, descriptions, source_ref):
    path = Path(out_root) / "data" / "params" / scenario / f"{source}.yaml"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(emit_data_text(scenario, source, records, descriptions, source_ref),
                    encoding="utf-8")
    return path
